---
  - name: Fedora machine setup
    hosts: localhost
    connection: local
    vars_files:
      - vars/vars_fedora.yml

    tasks:
      - name: Installing base system tools
        become: yes
        dnf: name={{ packages_base }} state=present

      - name: Installing editors
        become: yes
        dnf: name={{ packages_editor }} state=present

      - name: Installing devel tools
        become: yes
        dnf: name={{ packages_devel }} state=present

      - name: Installing utilities
        become: yes
        dnf: name={{ packages_utilities }} state=present

      - name: Installing productivity packages
        become: yes
        dnf: name={{ packages_productivity }} state=present

      - name: Installing sound packages
        become: yes
        dnf: name={{ packages_sound }} state=present

      - name: Installing additional programming tools
        become: yes
        dnf: name={{ packages_programming }}  state=present

      - name: Installing x11 tools
        become: yes
        dnf: name={{ packages_x11 }}  state=present

      - name: Installing desktop tools
        become: yes
        dnf: name={{ packages_desktop }} state=present

      - name: Installing fonts
        become: yes
        dnf: name={{ packages_fonts}} state=present

      - name: Installing backup tools
        become: yes
        dnf: name={{ packages_backup }} state=present

      - name: Installing security tools
        become: yes
        dnf: name={{ packages_sec }} state=present

      - name: Copy doas.conf defaults
        become: yes
        ansible.builtin.copy:
          content: 'permit keepenv :wheel'
          dest: '/etc/doas.conf'
          force: 'no'
          owner: 'root'
          group: 'root'
          mode: '0400'

      - name: "Downloading rclip-client"
        become: yes
        become_user: '{{ create_user }}'
        get_url:
          url: '{{ github_release_url_rclip }}'
          dest: '{{ github_dest_archive_rclip }}'

      - name: Extract rclip-client
        become: yes
        become_user: '{{ create_user }}'
        shell: |
          cd /tmp
          tar xf {{ github_dest_archive_rclip }} --strip-components=1
          rm {{ github_dest_archive_rclip }}

      - name: "Copy rclip-client binaries"
        become: yes
        copy: src='{{item.src}}' dest='{{item.dest}}' mode='a+x'
        with_items:
          - src: '/tmp/rclip-client-cli' dest: '{{ custom_binaries_folder }}/rclip-client-cli'
          - src: '/tmp/rclip-client-gui dest: '{{ custom_binaries_folder }}/rclip-client-gui
          
