---
  - name: NetBSD machine setup
    hosts: localhost
    connection: local
    become_method: su
    vars_files:
      - vars/vars_netbsd.yml

    tasks:
      - name: Installing base system tools
        become: yes
        community.general.pkgin: name={{ packages_base }} state=present

      - name: Installing editors
        become: yes
        community.general.pkgin: name={{ packages_editor }} state=present

      - name: Installing devel tools
        become: yes
        community.general.pkgin: name={{ packages_devel }} state=present

      - name: Installing utilities
        become: yes
        community.general.pkgin: name={{ packages_utilities }} state=present

      - name: Installing productivity packages
        become: yes
        community.general.pkgin: name={{ packages_productivity }} state=present

      - name: Installing sound packages
        become: yes
        community.general.pkgin: name={{ packages_sound }} state=present

      - name: Installing additional programming tools
        become: yes
        community.general.pkgin: name={{ packages_programming }}  state=present

      - name: Installing x11 tools
        become: yes
        community.general.pkgin: name={{ packages_x11 }}  state=present

      - name: Installing desktop tools
        become: yes
        community.general.pkgin: name={{ packages_desktop }} state=present

      - name: Installing fonts
        become: yes
        community.general.pkgin: name={{ packages_fonts}} state=present

      - name: Installing backup tools
        become: yes
        community.general.pkgin: name={{ packages_backup }} state=present

      - name: Installing security tools
        become: yes
        community.general.pkgin: name={{ packages_sec }} state=present

      - name: Creating user "{{ create_user }}"
        become: yes
        ansible.builtin.user:
          name: '{{ create_user }}'
          password: "{{ create_user_password | password_hash('sha512') }}"
          state: present
          groups: wheel
          append: true
          create_home: true
          skeleton: '{{ playbook_dir }}/skeletons'
          shell: /bin/ksh

      - name: Update password for user "{{ create_user }}"
        become: yes
        shell: "passwd {{ create_user }}"

      - name: Creating kshrc symlink for user "{{ create_user }}"
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.file:
          src: '/home/{{ create_user }}/.config/shell/kshrc'
          dest: '/home/{{ create_user }}/.kshrc'
          owner: '{{ create_user }}'
          state: link

      - name: Creating dot profile symlink for user "{{ create_user }}"
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.file:
          src: '/home/{{ create_user }}/.config/shell/profile'
          dest: '/home/{{ create_user }}/.profile'
          owner: '{{ create_user }}'
          state: link

      - name: Creating inputrc symlink for user "{{ create_user }}"
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.file:
          src: '/home/{{ create_user }}/.config/readline/inputrc'
          dest: '/home/{{ create_user }}/.inputrc'
          owner: '{{ create_user }}'
          state: link

      - name: Creating xsession symlink for user "{{ create_user }}"
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.file:
          src: '/home/{{ create_user }}/.config/x11/xsession'
          dest: '/home/{{ create_user }}/.xsession'
          owner: '{{ create_user }}'
          mode: '700'
          state: link

      - name: Generate borgmatic configuration for user "{{ create_user }}"
        become: yes
        become_user: '{{ create_user }}'
        template: src=./templates/borgmatic_config.yaml dest='/home/{{ create_user }}/.config/borgmatic/config.yaml'

      - name: Cloning dwm customization from Github
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.git:
          repo: '{{ github_repo_url_dwm }}'
          dest: '{{ github_repo_folder_dwm }}'

      - name: Cloning st terminal customization from Github
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.git:
          repo: '{{ github_repo_url_st }}'
          dest: '{{ github_repo_folder_st }}'

      - name: Compiling dwm
        become: yes
        become_user: '{{ create_user }}'
        make:
          chdir: '{{ github_repo_folder_dwm }}'

      - name: Compiling st
        become: yes
        become_user: '{{ create_user }}'
        make:
          chdir: '{{ github_repo_folder_st }}'

      - name: Create usr_local_bin folder
        ansible.builtin.file:
          path: /usr/local/bin
          state: directory
          mode: '0755'

      - name: "Downloading rclip-client"
        become: yes
        become_user: '{{ create_user }}'
        get_url:
          url: '{{ github_release_url_rclip }}'
          dest: '{{ github_dest_archive_rclip }}'

      - name: Extract rclip-client
        become: yes
        become_user: '{{ create_user }}'
        shell: |
          cd /tmp
          tar xf {{ github_dest_archive_rclip }} --strip-components=1
          rm {{ github_dest_archive_rclip }}

      - name: Copying custom binaries to "{{ custom_binaries_folder }}"
        become: yes
        copy: src={{ item.src }} dest={{ item.dest }} mode='a+x'
        with_items:
          - { src: Ëœ'{{ github_repo_folder_dwm }}/dwm', dest: '{{ custom_binaries_folder }}/dwm' }
          - { src: '{{ github_repo_folder_st }}/st', dest: '{{ custom_binaries_folder }}/st' }
          - { src: '/home/{{ create_user }}/.config/clipboard/rclip-copy', dest: '{{ custom_binaries_folder }}/rclip-copy' }
          - { src: '/home/{{ create_user }}/.config/clipboard/rclip-paste', dest: '{{ custom_binaries_folder }}/rclip-paste' }
          - { src: '/home/{{ create_user }}/.config/clipboard/rclip-xclip-copy', dest: '{{ custom_binaries_folder }}/rclip-xclip-copy' }
          - { src: '/home/{{ create_user }}/.config/clipboard/rclip-xclip-paste', dest: '{{ custom_binaries_folder }}/rclip-xclip-paste' }
          - { src: '/tmp/rclip-client-cli', dest: '{{ custom_binaries_folder }}/rclip-client-cli' }

      - name: Copy doas.conf defaults
        become: yes
        ansible.builtin.copy:
          content: 'permit keepenv :wheel'
          dest: '/usr/pkg/etc/doas.conf'
          force: 'no'
          owner: 'root'
          group: 'root'
          mode: '0400'
