---
  - name: Void Linux Setup
    hosts: localhost
    connection: local
    vars_files:
      - vars/default.yml

    tasks:
      - name: Install base system tools
        become: yes
        xbps: name={{ packages_base }} state=present

      - name: Install editors
        become: yes
        xbps: name={{ packages_editor }} state=present

      - name: Install devel tools
        become: yes
        xbps: name={{ packages_devel }} state=present

      - name: Install utilities
        become: yes
        xbps: name={{ packages_utilities }} state=present

      - name: Install productivity packages
        become: yes
        xbps: name={{ packages_productivity }} state=present

      - name: Install sound packages
        become: yes
        xbps: name={{ packages_sound }} state=present

      - name: Install additional programming tools
        become: yes
        xbps: name={{ packages_programming }}  state=present

      - name: Install x11 tools
        become: yes
        xbps: name={{ packages_x11 }}  state=present

      - name: Install desktop tools
        become: yes
        xbps: name={{ packages_desktop }} state=present

      - name: Install fonts
        become: yes
        xbps: name={{ packages_fonts}} state=present

      - name: Install backup tools
        become: yes
        xbps: name={{ packages_backup }} state=present

      - name: Install security tools
        become: yes
        xbps: name={{ packages_sec }} state=present

      - name: Create user
        become: yes
        ansible.builtin.user:
          name: '{{ create_user }}'
          state: present
          groups: wheel,audio,cdrom,floppy,input,lp,scanner,video
          append: true
          create_home: true
          skeleton: ./skel.d
          shell: /bin/oksh

      - name: kshrc link
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.file:
          src: '/home/{{ create_user }}/.config/shell/okshrc'
          dest: '/home/{{ create_user }}/.kshrc'
          owner: '{{ create_user }}'
          state: link

      - name: inputrc link
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.file:
          src: '/home/{{ create_user }}/.config/readline/inputrc'
          dest: '/home/{{ create_user }}/.inputrc'
          owner: '{{ create_user }}'
          state: link

      - name: xsession link
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.file:
          src: '/home/{{ create_user }}/.config/x11/xsessionrc'
          dest: '/home/{{ create_user }}/.xsessionrc'
          owner: '{{ create_user }}'
          state: link

      - name: xsession link
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.file:
          src: '/home/{{ create_user }}/.config/x11/xsession'
          dest: '/home/{{ create_user }}/.xsession'
          owner: '{{ create_user }}'
          mode: '700'
          state: link

      - name: Checkout dwm
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.git:
          repo: https://github.com/yveszoundi/dwm-customization.git
          dest: '/tmp/dwm-custom'

      - name: Checkout st
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.git:
          repo: https://github.com/yveszoundi/st-customization.git
          dest: '/tmp/st-custom'

      - name: Checkout boomer
        become: yes
        become_user: '{{ create_user }}'
        ansible.builtin.git:
          repo: https://github.com/yveszoundi/boomer.git
          dest: '/tmp/boomer-custom'        

      - name: Compile dwm
        become: yes
        become_user: '{{ create_user }}'
        make:
          chdir: '/tmp/dwm-custom'

      - name: Compile st
        become: yes
        become_user: '{{ create_user }}'
        make:
          chdir: '/tmp/st-custom'

      - name: Compile boomer
        become: yes
        ansible.builtin.shell:
          chdir: '/tmp/boomer-custom'
          cmd: nimble build

      - name: Copy custom binaries
        become: yes
        copy: src={{ item.src }} dest={{ item.dest }}
        with_items:
          - { src: '/tmp/dwm-custom/dwm', dest: '/usr/local/bin/dwm' }
          - { src: '/tmp/st-custom/st', dest: '/usr/local/bin/st' }
          - { src: '/tmp/boomer-custom/boomer', dest: '/usr/local/bin/boomer' }


        
          
