---
create_user: 'vip'
packages_base: ['oksh','lrzip','screen']
packages_sec: ['veracrypt', 'keepassxc' , 'encfs']
packages_editor: ['emacs', 'mg']
packages_devel: ['base-devel','libXft-devel','libXinerama-devel']
packages_utilities: ['ripgrep','git','gnupg']
packages_java: ['openjdk11','apache-maven','gradle']
packages_productivity: ['mypaint','ImageMagick','graphviz','ghostscript','atril']
packages_sound: ['alsa-utils','pulseaudio']
packages_x11: ['xorg','wmname','xdm','elogind']
packages_desktop: ['gvfs','pcmanfm','firefox']
packages_fonts: ['cantarell-fonts','terminus-font','liberation-fonts-ttf','noto-fonts-ttf','dejavu-fonts-ttf']
packages_backup: ['borgmatic','rsync','rclone']
